server:
  port: 8106

spring:
  jackson:
    modules-to-install:
      - com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  application:
    name: auth-service
  config:
    import:
      - optional:nacos:auth-service.yaml?server-addr=192.168.18.133:8848
  cloud:
    nacos:
      server-addr: 192.168.18.133:8848
      config:
        enabled: true
        namespace: public
    sentinel:
      transport:
        dashboard: 192.168.18.133:8080
        port: 8719
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            data-id: ${spring.application.name}-sentinel-flow
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            data-id: ${spring.application.name}-sentinel-degrade
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: degrade
    feign:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.18.133:3306/new-near-sync?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.18.133
      port: 6379
      password: ""
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web

knife4j:
  enable: true
  setting:
    language: zh_cn
    
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
  circuitbreaker:
    enabled: true
    alphanumericIds:
      enabled: true
