server:
  port: 8106

spring:
  application:
    name: auth-service
  config:
    import:
      - optional:nacos:auth-service.yaml?server-addr=192.168.18.130:8848
  cloud:
    nacos:
      server-addr: 192.168.18.130:8848
      config:
        enabled: true
        namespace: public
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.18.130:3306/new-near-sync?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.18.130
      port: 6379
      password: ""
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web

knife4j:
  enable: true
  setting:
    language: zh_cn
